### ISSUE TITLE
Is Codemod has been tried on Cucumber protractor framework based project migration?

### ISSUE THREAD

**Issue by santosjister** [webdriverio/codemod#72] opened 2022-09-21 14:15 UTC
Hi Team,

Is Codemod has been tried on Cucumber protractor framework based project migration? When i try with the migration as per the procedure provided in 'https://webdriver.io/docs/protractor-migration' (with my realtime project instead of boilerplate project), every alternative lines i am getting error and manually i have to correct it. This is hectic process.

Sometime the error is very generic like 'Unexpected token, expected "{", got this error on the first 'async' line of below code.

Sample code which i am trying to convert.

 @then('the user should be navigated to the personal details page')
  async theUserShouldBeNavigatedToThePersonalDetailsPage(): Promise<void> {
    const url = await browser.getCurrentUrl();
    assert.isTrue(url.endsWith('Userprofile'));
  }

Is there something i am missing ? Do i need to refer something else instead of 'https://webdriver.io/docs/protractor-migration' ?

Please advice on this.

**Comment by christian-bromann** [comment] 2022-09-21 15:41
> Is there something i am missing ?

The codemod currently doesn't support TypeScript (see also #28) which is why you are getting these errors. At this point I can only recommend to migrate manually given that I don't have the capacities to ship TS support anytime soon. Any contributions that help with TS support are very much appreciated.

I will close this as:
Duplicate of #28

**Closed by christian-bromann** 2022-09-21 15:41 UTC
